Build:
  stage: build
  rules:
    - when: on_success
  script:
    - nuget restore
    - msbuild SqlCompactExport.sln /p:Configuration=Release
  artifacts:
    name: Binary
    paths:
      - $CI_PROJECT_DIR/SqlCompactExport/bin/Release/*.exe
  tags:
    - build
  needs:
    - job: Test
      artifacts: false